### ISSUE TITLE
Release Checklist - v1.0.0

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/base-converter#22]
Tasks required for the next major release

## Features
- [ ] Better CLI output
- [ ] Handle any number conversions

## Fixes
- [ ] Move main script to main module
- [ ] Rename main module
- [ ] Drop force OOP

## Build
- [ ] Add linting stage to CI
- [ ] Auto publish to PyPi
- [ ] Create dockerfile for use

## Docs
- [ ] Publish API docs
- [ ] Migrate to google docstrings
- [ ] Create site to show usage
